# Generated by Django 4.2.1 on 2023-06-17 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportista', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportistauser',
            name='bez_veze',
            field=models.IntegerField(default=1),
        ),
    ]
