# Generated by Django 4.2.1 on 2023-06-18 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportista', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='plays_sport',
        ),
        migrations.CreateModel(
            name='TeamInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reciver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_reciver', to='sportista.sportistauser')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_sender', to='sportista.sportistauser')),
            ],
        ),
        migrations.CreateModel(
            name='PlayInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('start', models.DateTimeField()),
                ('ends', models.DateTimeField()),
                ('invite_reciver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_invite_reciver', to='sportista.sportistauser')),
                ('invite_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_invite_sender', to='sportista.sportistauser')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_sport', to='sportista.sport')),
            ],
        ),
    ]
