# Generated by Django 4.2.1 on 2023-06-18 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportista', '0003_remove_sportistauser_bez_veze'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_reciver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_reciver', to='sportista.sportistauser')),
                ('id_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_sender', to='sportista.sportistauser')),
            ],
        ),
        migrations.CreateModel(
            name='PlayInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_invite_reciver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_invite_reciver', to='sportista.sportistauser')),
                ('id_invite_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_invite_sender', to='sportista.sportistauser')),
            ],
        ),
    ]
