# Generated by Django 4.2.1 on 2023-06-18 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportista', '0004_teaminvite_playinvite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playinvite',
            old_name='id_invite_reciver',
            new_name='invite_reciver',
        ),
        migrations.RenameField(
            model_name='playinvite',
            old_name='id_invite_sender',
            new_name='invite_sender',
        ),
        migrations.RenameField(
            model_name='teaminvite',
            old_name='id_reciver',
            new_name='reciver',
        ),
        migrations.RenameField(
            model_name='teaminvite',
            old_name='id_sender',
            new_name='sender',
        ),
    ]
