# Generated by Django 4.2.1 on 2023-06-18 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportista', '0005_rename_id_invite_reciver_playinvite_invite_reciver_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='plays_sport',
        ),
    ]
