# Generated by Django 4.2.1 on 2023-06-15 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportista', '0006_alter_inbox_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamrentsfield',
            name='canceled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teamrentsfield',
            name='played',
            field=models.BooleanField(default=False),
        ),
    ]
