# Generated by Django 4.2.2 on 2023-06-15 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportista', '0006_alter_inbox_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbox',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
