# Generated by Django 4.2.1 on 2023-06-15 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportista', '0007_teamrentsfield_canceled_teamrentsfield_played'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamrentsfield',
            old_name='canceled',
            new_name='cancelled',
        ),
    ]
