# Generated by Django 4.2.1 on 2023-06-15 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportista', '0008_rename_canceled_teamrentsfield_cancelled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='grades',
        ),
    ]
