# Generated by Django 4.2.1 on 2023-06-16 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportista', '0007_inbox_archived'),
        ('sportista', '0009_remove_field_grades'),
    ]

    operations = [
    ]
