# Generated by Django 4.2.1 on 2023-06-17 12:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportista', '0010_merge_0007_inbox_archived_0009_remove_field_grades'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportistauser',
            name='friday_end',
            field=models.TimeField(default=datetime.time(17, 0)),
        ),
        migrations.AddField(
            model_name='sportistauser',
            name='friday_start',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
        migrations.AddField(
            model_name='sportistauser',
            name='monday_end',
            field=models.TimeField(default=datetime.time(17, 0)),
        ),
        migrations.AddField(
            model_name='sportistauser',
            name='monday_start',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
        migrations.AddField(
            model_name='sportistauser',
            name='saturday_end',
            field=models.TimeField(default=datetime.time(17, 0)),
        ),
        migrations.AddField(
            model_name='sportistauser',
            name='saturday_start',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
        migrations.AddField(
            model_name='sportistauser',
            name='sunday_end',
            field=models.TimeField(default=datetime.time(17, 0)),
        ),
        migrations.AddField(
            model_name='sportistauser',
            name='sunday_start',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
        migrations.AddField(
            model_name='sportistauser',
            name='thursday_end',
            field=models.TimeField(default=datetime.time(17, 0)),
        ),
        migrations.AddField(
            model_name='sportistauser',
            name='thursday_start',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
        migrations.AddField(
            model_name='sportistauser',
            name='tuesday_end',
            field=models.TimeField(default=datetime.time(17, 0)),
        ),
        migrations.AddField(
            model_name='sportistauser',
            name='tuesday_start',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
        migrations.AddField(
            model_name='sportistauser',
            name='wednesday_end',
            field=models.TimeField(default=datetime.time(17, 0)),
        ),
        migrations.AddField(
            model_name='sportistauser',
            name='wednesday_start',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
    ]
